### ISSUE TITLE
nerfacc rendering gradient error

### ISSUE THREAD

**Issue by SYSUykLin** [nerfstudio-project/nerfacc#266]
I render image by 
`    # Differentiable Volumetric Rendering.
    # colors: (n_rays, 3). opaicity: (n_rays, 1). depth: (n_rays, 1).
    results['rgb'], results['opacity'], results['depth'], results['vr_samples'] = nerfacc.rendering(t_starts=t_starts, t_ends=t_ends, 
                                                                                                    ray_indices=ray_indices, n_rays=rays_o.shape[0], 
                                                                                                    rgb_sigma_fn=rgb_sigma_fn)`
And print( results['rgb'].required_grad) is False, why?

Thx

**Comment by dragonwarrior** [comment]
i had a similar problem that 'nerfacc.rendering' can't bp gradients, why

**Comment by dragonwarrior** [comment]
yes, i used estimator.sample api.
right now, i solved my problem, it's because another mistake made by myself. the api is ok.
