### ISSUE TITLE
About Compilation

### ISSUE THREAD

**Issue by myc634** [nerfstudio-project/nerfacc#273]
Thanks for your contribution! I had the following question the first time I ran this:
`/miniconda3/envs/mmdet3d-0.17.0/lib/python3.8/site-packages/nerfacc/cuda/csrc/grid.cu:4:10: fatal error: ATen/cuda/CUDAGeneratorImpl.h: No such file or 
directory`

My pytorch version is 1.10 and uses CUDA 11.3, can you give me some instructions on how to solve this?

**Comment by limaolin2017** [comment]
Same issues..

**Comment by limaolin2017** [comment]
how did you fix it?

**Comment by myc634** [comment]
Upgrade torch vision to at least 1.13 works for me

**Comment by limaolin2017** [comment]
Is it above 11.3?

maoyucheng0321 ***@***.***> 于2024年2月10日周六 03:58写道：
