### ISSUE TITLE
Sum instead of Product in scan_cub.cu

### ISSUE THREAD

**Issue by kirchhart-intel** [nerfstudio-project/nerfacc#284]
https://github.com/nerfstudio-project/nerfacc/blob/bfbf0278d8fba00ca517956895ed71d71e6db163/nerfacc/cuda/csrc/scan_cub.cu#L274

https://github.com/nerfstudio-project/nerfacc/blob/bfbf0278d8fba00ca517956895ed71d71e6db163/nerfacc/cuda/csrc/scan_cub.cu#L205

I believe this should call the “product” routines, not the “sum” routines.

**Comment by liruilong940607** [comment]
Nah if you write out the math for backward, you would be surprised that the sum routines is the correct implementation.
