### ISSUE TITLE
.data_ptr<long>() in scan_cub.cu need to be replaced with .data_ptr<int64_t>() for correct operation on Windows

### ISSUE THREAD

**Issue by asupikov** [nerfstudio-project/nerfacc#293]
Currently, nerfacc crashes on Win because long resolves to int32_t there rather than int64_t like on Linux.

**Comment by skywolf829** [comment]
Commenting to bump this. Installation failed on my Windows machine until I fixed this as well.
As an aside, installation on WSL worked just fine without any changes.
